osx_image: xcode8.3

dist: trusty
sudo: false

branches:
  only:
  - master
  - develop
  - production

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds


install:
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "production" ]; then npm run site-prod && npm run dist-mac-prod; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run site-staging && npm run dist-mac-staging; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run site-dev && npm run dist-mac-dev; fi


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"