platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'



init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install


for:

-
  branches:
    only:
      - master

  build_script:
    - npm run dist-win-staging

-
  branches:
    only:
      - production

  build_script:
    - npm run dist-win-prod

-
  branches:
    only:
      - develop

  build_script:
    - npm run dist-win-dev

test: off
