platform:
  - x64

branches:
    only:
      - master
      - develop
      - production

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'


init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install

for:

-
  branches:
    only:
      - master
  environment:
    SITE: https://unomi-staging.enkonix.com/

  build_script:
    - npm run site-staging
    - npm run dist-win-staging

-
  branches:
    only:
      - production
  environment:
    SITE: https://getunomi.com/

  build_script:
    - npm run site-prod
    - npm run dist-win-prod

-
  branches:
    only:
      - develop
      
  environment:
    SITE: https://unomi-develop.enkonix.com/

  build_script:
    - npm run site-dev
    - npm run dist-win-dev

test: off
